(()=>{'use strict';
const $=s=>document.querySelector(s),preview=$('#appPreview'),optics=$('#optics'),errors=[],runs=[];let preset=null,playing=false,live=false,opticsState=null;
const issue=(realm,message)=>{if(errors.length<80)errors.push({realm,message:String(message).slice(0,800),time:new Date().toISOString()})};
addEventListener('error',e=>issue('diagnostics',e.message));addEventListener('unhandledrejection',e=>issue('diagnostics',e.reason?.message||e.reason));
for(const [name,frame]of [['preview',preview],['optics',optics]])frame.addEventListener('load',()=>{try{frame.contentWindow.addEventListener('error',e=>issue(name,e.message));frame.contentWindow.addEventListener('unhandledrejection',e=>issue(name,e.reason?.message||e.reason))}catch(e){issue(name,e.message)}});
function send(type,extra={}){preview.contentWindow.postMessage({source:'vf-editor',type,...extra},location.origin)}
addEventListener('message',e=>{if(e.origin!==location.origin)return;if(e.source===optics.contentWindow&&e.data?.source==='vf-optics-diagnostic')opticsState=e.data;if(e.source!==preview.contentWindow||e.data?.source!=='vf-motion')return;if(e.data.type==='error')issue('motion',e.data.message);if(e.data.type==='ready'){preset=e.data.profile;$('#play').disabled=$('#live').disabled=false;$('#performance').textContent='Док готовий. Пресет прочитано без збереження змін.'}});
function collectLayers(doc){return [...doc.querySelectorAll('.quick-entry-shell,.dock-indicator,#dockZoomSurfaces,#dockZoomSurfaces > span,.profile-drawer,.sheet,.vf-contour-zoom-layer,.vf-rgb-channel')].slice(0,100).map(node=>{const c=doc.defaultView.getComputedStyle(node),r=node.getBoundingClientRect();return {element:node.id||node.className,channel:node.dataset.channel||null,rect:{x:r.x,y:r.y,width:r.width,height:r.height},filter:c.filter,backdropFilter:c.backdropFilter||c.webkitBackdropFilter,mask:c.maskImage||c.webkitMaskImage,transform:c.transform,opacity:c.opacity,zIndex:c.zIndex,display:c.display}})}
function report(){const doc=preview.contentDocument;return {schema:'liquid-studio-device-diagnostic-v2',build:109,time:new Date().toISOString(),device:{userAgent:navigator.userAgent,platform:navigator.platform,touchPoints:navigator.maxTouchPoints,dpr:devicePixelRatio,screen:{width:screen.width,height:screen.height},viewport:{width:innerWidth,height:innerHeight,visualWidth:visualViewport?.width,visualHeight:visualViewport?.height,offsetTop:visualViewport?.offsetTop},standalone:!!navigator.standalone||matchMedia('(display-mode: standalone)').matches},capabilities:{share:!!navigator.share,cssFilter:CSS.supports('filter','url(#test)'),backdropBlur:CSS.supports('backdrop-filter','blur(2px)')||CSS.supports('-webkit-backdrop-filter','blur(2px)'),mask:CSS.supports('mask-image','linear-gradient(black,transparent)')||CSS.supports('-webkit-mask-image','linear-gradient(black,transparent)')},warning:'CSS support and frame timings do not prove visual correctness. RGB/animation observations are supplied by the user.',observations:{rgb:$('#rgbResult').value,animations:$('#animationResult').value,note:$('#note').value.slice(0,4000)},opticsState,runs,webgl:preview.contentWindow.VFMirror?.diagnostics?.()||null,transitionTrace:preview.contentWindow.VFDiagnosticTrace?.snapshot()||null,errors,earlyErrors:{preview:preview.contentWindow.VFDiagnosticErrors||[],optics:optics.contentWindow.VFDiagnosticErrors||[]},preset,layers:doc?collectLayers(doc):[],rgbFilters:doc?[...doc.querySelectorAll('filter[id^="vf-radial-"]')].slice(0,50).map(f=>({id:f.id,scale:f.querySelector('feDisplacementMap')?.getAttribute('scale'),map:f.querySelector('feImage')?.hasAttribute('href')})):[]}}
$('#play').onclick=()=>{if(!preset||playing)return;playing=true;live=false;preview.contentWindow.VFDiagnosticTrace?.start({mode:'playback',transition:$('#transition').value});$('#compact').disabled=true;$('#live').textContent='Живий режим';send('live-preview',{enabled:false});const name=$('#transition').value,popup=['drawer','sheet'].includes(name)?name:null,tr=popup?preset.popups[popup]:preset.transitions[name],duration=tr.duration,intervals=[];let began,last;$('#play').disabled=true;const tick=now=>{if(began===undefined)began=last=now;else{intervals.push(now-last);last=now}const t=Math.min(1,(now-began)/duration);send('seek',{transition:popup?'expand':name,popup,t});if(t<1)requestAnimationFrame(tick);else{playing=false;$('#play').disabled=false;const sorted=intervals.slice().sort((a,b)=>a-b),average=intervals.reduce((a,b)=>a+b,0)/Math.max(1,intervals.length),result={name,duration,frames:intervals.length,meanIntervalMs:average,p95IntervalMs:sorted[Math.floor((sorted.length-1)*.95)]||0,longFrames:intervals.filter(v=>v>34).length,visibility:document.visibilityState};runs.push(result);if(runs.length>20)runs.shift();preview.contentWindow.VFDiagnosticTrace?.stop();$('#performance').textContent=`${name}: ${Math.round(duration)} ms; ${intervals.length} кадрів; середній інтервал ${average.toFixed(1)} ms. Це частота викликів, не доказ відсутності блимання.`}};requestAnimationFrame(tick)};
$('#live').onclick=()=>{if(playing)return;live=!live;if(live)preview.contentWindow.VFDiagnosticTrace?.start({mode:'live',transition:'interactive'});else preview.contentWindow.VFDiagnosticTrace?.stop();send('live-preview',{enabled:live,profile:preset});$('#live').textContent=live?'Вийти з живого режиму':'Живий режим';$('#compact').disabled=!live;if(!live)send('seek',{transition:'expand',t:1,popup:null})};$('#compact').onclick=()=>send('toggle-dock');
const text=()=>JSON.stringify(report(),null,2),status=message=>$('#status').textContent=message;
$('#viewReport').onclick=()=>{const box=$('#reportText');box.hidden=false;box.value=text();status('Звіт сформовано. Можна переглянути або скопіювати вручну.')};
$('#download').onclick=()=>{const url=URL.createObjectURL(new Blob([text()],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='liquid-studio-iphone-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);status('Звіт сформовано. Прикріпи JSON у цьому чаті разом із записом екрана.')};
$('#copy').onclick=async()=>{const value=text();try{await navigator.clipboard.writeText(value);status('Звіт скопійовано.')}catch{const box=$('#reportText');box.hidden=false;box.value=value;box.focus();box.select();status('Виділи й скопіюй звіт вручну або завантаж JSON.')}};
$('#share').onclick=async()=>{try{const file=new File([text()],'liquid-studio-iphone-report.json',{type:'application/json'});if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'Liquid Studio · діагностика iPhone'});status('Звіт передано через меню iPhone.')}else{status('Обмін файлами недоступний. Скористайся «Завантажити JSON» або «Копіювати звіт».')}}catch(e){status(e.name==='AbortError'?'Надсилання скасовано.':'Не вдалося поділитися. Завантаж JSON або скопіюй звіт.')}};
})();
