(()=>{'use strict';
const $=s=>document.querySelector(s),copy=x=>JSON.parse(JSON.stringify(x)),iframe=$('#preview');
let profile,tab='dock',transition='expand',popup='drawer',selected=0,t=0,playing=false,raf,history=[],future=[];
const key='vf-liquid-motion-v1',status=s=>$('#status').textContent=s;
$('#element').value='entry';
const track=()=>tab==='dock'?profile.transitions[transition]:profile.popups[popup];
const send=(type,extra={})=>iframe.contentWindow.postMessage({source:'vf-editor',type,transition,t,popup:tab==='popup'?popup:null,...extra},location.origin);
function remember(){history.push(JSON.stringify(profile));if(history.length>60)history.shift();future=[]}
function persist(){try{localStorage.setItem(key+'-draft',JSON.stringify(profile));status('Чернетку збережено на цьому пристрої')}catch{status('Не вдалося зберегти. Експортуй файл.')}send('preset',{profile});$('#undo').disabled=!history.length;$('#redo').disabled=!future.length}
function change(fn,redraw=false){remember();fn();persist();if(redraw)render()}
function control(root,label,value,min,max,step,set,type='number'){
 const el=document.createElement('div');el.className='control';const row=document.createElement('label');row.className='row';const text=document.createElement('span');text.textContent=label;const n=document.createElement('input');n.type=type;n.value=value;n.setAttribute('aria-label',label);row.append(text,n);el.append(row);
 if(type==='number'){n.min=min;n.max=max;n.step=step;const range=document.createElement('input');Object.assign(range,{type:'range',min,max,step,value});range.setAttribute('aria-label',label+' — повзунок');let editing=false;range.onpointerdown=()=>{remember();editing=true};range.oninput=()=>{if(!editing){remember();editing=true}n.value=range.value;set(+range.value);persist();updateCurve()};range.onchange=()=>editing=false;n.onchange=()=>{const v=Math.min(max,Math.max(min,+n.value));if(!Number.isFinite(v))return;n.value=range.value=v;change(()=>set(v));updateCurve()};el.append(range)}else n.onchange=()=>change(()=>set(n.value));root.append(el)
}
function fields(root,obj,specs){root.replaceChildren();for(const [k,label,min,max,step,type]of specs)control(root,label,obj[k],min,max,step,v=>obj[k]=v,type)}
function updateCurve(){if(!profile)return;const c=track().curve;$('#curvePath').setAttribute('d',`M 10 100 C ${10+c[0]*180} ${100-c[1]*90}, ${10+c[2]*180} ${100-c[3]*90},190 10`)}
function selectKey(i){selected=i;t=track().frames[i].t;seek();render()}
function seek(){ $('#scrub').value=t*1000;$('#time').textContent=Math.round(t*track().duration)+' ms';send('seek'); }
function renderKeys(){
 const root=$('#keys');root.replaceChildren();track().frames.forEach((f,i)=>{
  const b=document.createElement('button');b.textContent='◆';b.title=`Ключ ${i+1}: ${Math.round(f.t*100)}%`;b.setAttribute('aria-label',b.title);b.style.left=f.t*100+'%';b.classList.toggle('selected',i===selected);b.onclick=()=>selectKey(i);
  b.onpointerdown=e=>{if(i===0||i===track().frames.length-1)return;stop();selected=i;t=f.t;seek();geometry();let moved=false;b.setPointerCapture(e.pointerId);
   b.onpointermove=ev=>{if(!moved){remember();moved=true}const box=root.getBoundingClientRect();f.t=Math.max(track().frames[i-1].t+.005,Math.min(track().frames[i+1].t-.005,(ev.clientX-box.left)/box.width));t=f.t;b.style.left=f.t*100+'%';$('#keyTime').value=(f.t*100).toFixed(1);seek()};
   b.onpointerup=()=>{b.onpointermove=null;if(moved)persist();render()};b.onpointercancel=()=>{b.onpointermove=null;render()};
  };root.append(b)
 });$('#keyTime').value=(track().frames[selected].t*100).toFixed(1);$('#keyTime').disabled=selected===0||selected===track().frames.length-1;$('#remove').disabled=$('#keyTime').disabled;
}
function geometry(){const root=$('#geometry');root.replaceChildren();const f=track().frames[selected];if(tab==='popup'){['X, %','Y, %','Масштаб','Прозорість'].forEach((label,j)=>control(root,label,f.v[j],j<2?-150:0,j<2?150:j===2?2:1,.01,v=>f.v[j]=v));return}
 const k=$('#element').value,s=f.state,a=k.startsWith('button')?s.buttons[+k.slice(6)]:s[k];
 ['X, px','Y, px','Ширина, px','Висота, px','Заокруглення, px','Прозорість'].forEach((label,j)=>control(root,label,a[j],j<2?-200:0,j<2?700:j<5?700:1,j===5?.01:1,v=>{const delta=v-a[j];a[j]=v;const rim={entry:'entryRim',nav:'navRim',active:'activeRim'}[k];if(rim)s[rim][j]=v;if(k==='entry'){s.entryHtml[j]=j<2?v-14:v}if(k==='nav'||k==='active'){const indexes=k==='nav'?[3,4]:[0,1,2];if(j<2)indexes.forEach(i=>s.buttons[i][j]+=delta)}}));
 if(k==='entry')for(const [j,label,max]of [[7,'Відступ зліва',60],[8,'Відступ справа',60],[10,'Розмір плюса',50],[11,'Кнопка відправлення',70],[12,'Стрілка відправлення',40]])control(root,label,s.entryHtml[j],0,max,1,v=>s.entryHtml[j]=v);
 if(k.startsWith('button')){control(root,'Масштаб кнопки',a[6],.2,2,.01,v=>a[6]=v);control(root,'Прозорість підпису',a[7],0,1,.01,v=>a[7]=v)}
 const own=document.createElement('details'),title=document.createElement('summary');title.textContent='Власний матеріал цього елемента';own.append(title);root.append(own);const m=profile.surfaces?.[k]||{color:k==='indicator'?'#09090a':k.startsWith('button')?'#ffffff':profile.material.color,opacity:1,blur:profile.material.blur,border:0};for(const [prop,label,min,max,step,type]of [['color','Колір елемента',0,0,0,'color'],['opacity','Прозорість елемента',0,1,.01],['blur','Розмиття елемента',0,40,1],['border','Обводка елемента',0,8,.1]])control(own,label,m[prop],min,max,step,v=>{m[prop]=v;(profile.surfaces??={})[k]=m},type);
}
function render(){if(!profile)return;selected=Math.min(selected,track().frames.length-1);geometry();renderKeys();const timing=$('#timing');timing.replaceChildren();control(timing,'Тривалість, ms',track().duration,80,5000,10,v=>track().duration=v);['Початок X','Початок Y','Кінець X','Кінець Y'].forEach((label,i)=>control(timing,label,track().curve[i],0,1,.01,v=>track().curve[i]=v));updateCurve();
 fields($('#material'),tab==='dock'?profile.material:profile.popups[popup],tab==='dock'?[['color','Колір',0,0,0,'color'],['opacity','Прозорість',0,1,.01],['blur','Розмиття',0,40,1],['lens','Лінза / блиск',0,3,.05],['border','Обводка, px',0,8,.1],['borderOpacity','Прозорість обводки',0,1,.01],['indicator','Індикатор',0,0,0,'color'],['accent','Активна кнопка',0,0,0,'color']]:[['color','Колір',0,0,0,'color'],['opacity','Прозорість скла',0,1,.01],['blur','Розмиття',0,40,1],['radius','Кути, px',0,80,1],['border','Обводка, px',0,8,.1]]);
 if(tab==='popup'){const q=profile.popups[popup];control($('#material'),'Ширина вікна, px',q.width|| (popup==='drawer'?360:480),200,900,1,v=>q.width=v);control($('#material'),'Макс. висота, % екрана',q.height||90,20,100,1,v=>q.height=v)}
 const l=$('#liquid');fields(l,profile.liquid,[['strength','Деформація',0,3,.05],['reach','Відстань злиття, px',0,250,1],['neck','Товщина перешийка',0,3,.05],['tension','Натяг краю',.05,.9,.01],['blur','М’якість злиття',0,8,.1]]);const label=document.createElement('label'),toggle=document.createElement('input');toggle.type='checkbox';toggle.checked=profile.liquid.enabled;toggle.onchange=()=>change(()=>profile.liquid.enabled=toggle.checked);label.append(toggle,' Зливання крапель');l.prepend(label);$('#undo').disabled=!history.length;$('#redo').disabled=!future.length;
}
function stop(){playing=false;cancelAnimationFrame(raf);$('#play').textContent='▶ Відтворити'}
$('#play').onclick=()=>{if(playing){stop();return}playing=true;$('#play').textContent='Ⅱ Пауза';if(t>=1)t=0;const start=performance.now()-t*track().duration;const tick=now=>{t=((now-start)/track().duration);if(t>=1){if($('#loop').checked)t%=1;else{t=1;seek();stop();return}}seek();raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick)};
$('#scrub').oninput=e=>{stop();t=+e.target.value/1000;seek()};$('#start').onclick=()=>{stop();t=0;seek()};
$('#transition').onchange=e=>{stop();transition=e.target.value;selected=0;t=0;render();persist()};$('#popup').onchange=e=>{popup=e.target.value;selected=0;t=0;render();persist()};$('#element').onchange=geometry;
function setTab(value){stop();tab=value;t=0;selected=0;$('#dockTab').classList.toggle('selected',tab==='dock');$('#popupTab').classList.toggle('selected',tab==='popup');$('#transition').parentElement.hidden=tab!=='dock';$('#popupChoice').hidden=tab==='dock';$('#element').hidden=tab!=='dock';render();persist()}
$('#dockTab').onclick=()=>setTab('dock');$('#popupTab').onclick=()=>setTab('popup');
$('#add').onclick=()=>{if(track().frames.some(f=>Math.abs(f.t-t)<.005)){status('На цій позиції вже є ключ');return}change(()=>{let f;if(tab==='dock'){const s=iframe.contentWindow.VFMotion.sample(transition,t);const r=profile.referenceWidth/s.w;for(const k of ['entry','entryRim','entryBulge','nav','active','navRim','activeRim','neck','drop','drop2','drop3','shine','entryHtml','indicator']){s[k][0]*=r;s[k][2]*=r}for(const b of s.buttons){b[0]*=r;b[2]*=r}s.w=profile.referenceWidth;f={t,state:s}}else{const fs=track().frames;let i=0;while(i<fs.length-2&&fs[i+1].t<t)i++;const a=fs[i],b=fs[i+1],u=(t-a.t)/(b.t-a.t);f={t,v:a.v.map((v,j)=>v+(b.v[j]-v)*u)}}track().frames.push(f);track().frames.sort((a,b)=>a.t-b.t);selected=track().frames.indexOf(f)},true)};
$('#remove').onclick=()=>{if(selected===0||selected===track().frames.length-1)return;change(()=>{track().frames.splice(selected,1);selected--;t=track().frames[selected].t},true)};
$('#keyTime').onchange=e=>{const fs=track().frames;if(selected===0||selected===fs.length-1)return;change(()=>{fs[selected].t=Math.max(fs[selected-1].t+.005,Math.min(fs[selected+1].t-.005,+e.target.value/100));t=fs[selected].t},true)};
document.querySelectorAll('[data-curve]').forEach(b=>b.onclick=()=>change(()=>track().curve=b.dataset.curve.split(',').map(Number),true));
$('#undo').onclick=()=>{if(!history.length)return;future.push(JSON.stringify(profile));profile=JSON.parse(history.pop());selected=0;persist();render()};$('#redo').onclick=()=>{if(!future.length)return;history.push(JSON.stringify(profile));profile=JSON.parse(future.pop());selected=0;persist();render()};
$('#width').onchange=e=>{iframe.style.width=e.target.value+'px';setTimeout(()=>send('preset',{profile}),100)};
$('#apply').onclick=()=>send('save',{profile});$('#disable').onclick=()=>{localStorage.removeItem(key);status('Пресет вимкнено. Перезавантаж застосунок.')};$('#reset').onclick=()=>{if(confirm('Скинути всі форми та налаштування чернетки?')){remember();send('reset')}};
$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(profile,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='voice-finance-motion.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('#import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>2000000)throw Error('Файл завеликий');const p=iframe.contentWindow.VFMotion.validate(JSON.parse(await file.text()));remember();profile=p;selected=0;t=0;persist();render()}catch(err){status('Імпорт: '+err.message)}e.target.value=''};
addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==iframe.contentWindow||e.data?.source!=='vf-motion')return;const d=e.data;if(d.type==='ready'){profile=d.profile;render();persist()}if(d.type==='error')status('Помилка: '+d.message);if(d.type==='saved')status('Застосовано! Відкрий або перезавантаж Demo.')});
})();
