(()=>{'use strict';
const $=s=>document.querySelector(s),copy=x=>JSON.parse(JSON.stringify(x)),iframe=$('#preview');
let profile,tab='dock',transition='expand',popup='drawer',selected=0,t=0,playing=false,raf,history=[],future=[];
const key='vf-liquid-motion-v1',status=s=>$('#status').textContent=s;
$('#element').value='entry';
const scene=()=>tab==='dock'?profile.transitions[transition]:profile.popups[popup];
const track=()=>tab==='dock'?scene().tracks[$('#element').value]:scene();
const keyMs=(f,tr=track())=>(tr.delay||0)+f.t*tr.duration;
const names={entry:'Поле введення',active:'Ліва крапля',nav:'Капсула',indicator:'Індикатор',button0:'Цілі',button1:'Аналітика',button2:'Борги',button3:'Дім',button4:'Додатково'};
const send=(type,extra={})=>iframe.contentWindow.postMessage({source:'vf-editor',type,transition,t,popup:tab==='popup'?popup:null,...extra},location.origin);
function remember(){history.push(JSON.stringify(profile));if(history.length>60)history.shift();future=[]}
function persist(){try{localStorage.setItem(key+'-draft',JSON.stringify(profile));status('Чернетку збережено на цьому пристрої')}catch{status('Не вдалося зберегти. Експортуй файл.')}send('preset',{profile});$('#undo').disabled=!history.length;$('#redo').disabled=!future.length}
function change(fn,redraw=false){stop();remember();fn();persist();render()}
function control(root,label,value,min,max,step,set,type='number'){
 const el=document.createElement('div');el.className='control';const row=document.createElement('label');row.className='row';const text=document.createElement('span');text.textContent=label;const n=document.createElement('input');n.type=type;n.value=value;n.setAttribute('aria-label',label);row.append(text,n);el.append(row);
 if(type==='number'){n.min=min;n.max=max;n.step=step;const range=document.createElement('input');Object.assign(range,{type:'range',min,max,step,value});range.setAttribute('aria-label',label+' — повзунок');let editing=false;const begin=()=>{if(!editing){stop();remember();editing=true}};const refresh=()=>{persist();renderKeys();seek();updateCurve()};range.onpointerdown=begin;range.oninput=()=>{begin();n.value=range.value;set(+range.value);refresh()};range.onchange=()=>{editing=false;render()};n.oninput=()=>{if(n.value===''||!Number.isFinite(+n.value))return;begin();const v=Math.min(max,Math.max(min,+n.value));range.value=v;set(v);refresh()};n.onchange=()=>{editing=false;render()};el.append(range)}else n.onchange=()=>change(()=>set(n.value));root.append(el)
}
function fields(root,obj,specs){root.replaceChildren();for(const [k,label,min,max,step,type]of specs)control(root,label,obj[k],min,max,step,v=>obj[k]=v,type)}
function updateCurve(){if(!profile)return;const c=track().curve;$('#curvePath').setAttribute('d',`M 10 100 C ${10+c[0]*180} ${100-c[1]*90}, ${10+c[2]*180} ${100-c[3]*90},190 10`)}
function selectKey(i){stop();selected=i;t=keyMs(track().frames[i])/scene().duration;seek();render()}
function seek(){ $('#scrub').value=t*1000;$('#time').textContent=Math.round(t*scene().duration)+' / '+Math.round(scene().duration)+' ms';document.querySelectorAll('.playhead').forEach(n=>n.style.left=t*100+'%');send('seek'); }
function renderKeys(){
 const root=$('#keys');root.replaceChildren();$('#ruler').replaceChildren();for(let i=0;i<5;i++){const n=document.createElement('span');n.textContent=(scene().duration*i/4000).toFixed(2)+'s';$('#ruler').append(n)}
 for(const [k,label]of (tab==='dock'?Object.entries(names):[[popup,popup==='drawer'?'Додатково':'Картка']])){const tr=tab==='dock'?scene().tracks[k]:scene(),row=document.createElement('div');row.className='track'+(tab==='popup'||k===$('#element').value?' active':'');const name=document.createElement('button');name.className='trackName';name.textContent=label;name.onclick=()=>{if(tab==='dock')$('#element').value=k;selectKey(0)};row.append(name);const lane=document.createElement('div');lane.className='lane';const clip=document.createElement('div');clip.className='clip';clip.style.left=(tr.delay||0)/scene().duration*100+'%';clip.style.width=tr.duration/scene().duration*100+'%';lane.append(clip);
 tr.frames.forEach((f,i)=>{const b=document.createElement('button');b.className='key';b.textContent='◆';b.setAttribute('aria-label',`${label}: ключ ${i+1}`);b.style.left=keyMs(f,tr)/scene().duration*100+'%';b.classList.toggle('selected',(tab==='popup'||k===$('#element').value)&&i===selected);b.onclick=()=>{if(tab==='dock')$('#element').value=k;selectKey(i)};
 b.onpointerdown=e=>{stop();if(tab==='dock')$('#element').value=k;selected=i;t=keyMs(f,tr)/scene().duration;seek();if(i===0||i===tr.frames.length-1)return;let moved=false;const startX=e.clientX;b.setPointerCapture(e.pointerId);b.onpointermove=ev=>{if(!moved&&Math.abs(ev.clientX-startX)<3)return;if(!moved){remember();moved=true}const box=lane.getBoundingClientRect(),ms=(ev.clientX-box.left)/box.width*scene().duration;f.t=Math.max(tr.frames[i-1].t+.005,Math.min(tr.frames[i+1].t-.005,(ms-(tr.delay||0))/tr.duration));t=keyMs(f,tr)/scene().duration;b.style.left=t*100+'%';seek()};b.onpointerup=()=>{b.onpointermove=null;if(moved)persist();render()};b.onpointercancel=()=>{b.onpointermove=null;if(moved)persist();render()}};lane.append(b)});
 const head=document.createElement('div');head.className='playhead';head.style.left=t*100+'%';lane.append(head);lane.onclick=e=>{if(e.target!==lane)return;stop();if(tab==='dock')$('#element').value=k;const r=lane.getBoundingClientRect();t=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width));selected=tr.frames.reduce((best,f,i)=>Math.abs(keyMs(f,tr)-t*scene().duration)<Math.abs(keyMs(tr.frames[best],tr)-t*scene().duration)?i:best,0);seek();renderKeys();$('#selection').textContent=label+' · «＋ Ключ» додасть форму тільки тут'};row.append(lane);root.append(row)}
 $('#remove').disabled=selected===0||selected===track().frames.length-1;$('#selection').textContent=(tab==='dock'?names[$('#element').value]:'Вікно')+' · ключ '+(selected+1)+' · '+Math.round(keyMs(track().frames[selected]))+' ms';
}
function geometry(){const root=$('#geometry');root.replaceChildren();const f=track().frames[selected];if(tab==='popup'){['X, %','Y, %','Масштаб','Прозорість'].forEach((label,j)=>control(root,label,f.v[j],j<2?-150:0,j<2?150:j===2?2:1,.01,v=>f.v[j]=v));return}
 const k=$('#element').value,s=f.state,a=k.startsWith('button')?s.buttons[+k.slice(6)]:s[k];
 ['X, px','Y, px','Ширина, px','Висота, px','Заокруглення, px','Прозорість'].forEach((label,j)=>control(root,label,a[j],j<2?-200:0,j<2?700:j<5?700:1,j===5?.01:1,v=>{a[j]=v;const rim={entry:'entryRim',nav:'navRim',active:'activeRim'}[k];if(rim)s[rim][j]=v;if(k==='entry')s.entryHtml[j]=j<2?v-14:v;t=keyMs(f)/scene().duration;seek()}));
 if(k==='entry')for(const [j,label,max]of [[7,'Відступ зліва',60],[8,'Відступ справа',60],[10,'Розмір плюса',50],[11,'Кнопка відправлення',70],[12,'Стрілка відправлення',40]])control(root,label,s.entryHtml[j],0,max,1,v=>s.entryHtml[j]=v);
 if(k.startsWith('button')){control(root,'Масштаб кнопки',a[6],.2,2,.01,v=>a[6]=v);control(root,'Прозорість підпису',a[7],0,1,.01,v=>a[7]=v)}
}
function render(){if(!profile)return;selected=Math.min(selected,track().frames.length-1);geometry();renderKeys();const timing=$('#timing');timing.replaceChildren();control(timing,'Тривалість усього переходу, ms',scene().duration,80,10000,10,v=>{const ratio=v/scene().duration;if(tab==='dock')Object.values(scene().tracks).forEach(tr=>{tr.duration*=ratio;tr.delay*=ratio});scene().duration=v});if(tab==='dock'){control(timing,'Тривалість елемента, ms',track().duration,80,10000-track().delay,10,v=>{track().duration=v;scene().duration=Math.max(scene().duration,v+track().delay)});control(timing,'Затримка елемента, ms',track().delay,0,10000-track().duration,10,v=>{track().delay=v;scene().duration=Math.max(scene().duration,v+track().duration)})}if(selected>0&&selected<track().frames.length-1)control(timing,'Час ключа, ms',keyMs(track().frames[selected]),keyMs(track().frames[selected-1])+1,keyMs(track().frames[selected+1])-1,1,v=>{track().frames[selected].t=(v-(track().delay||0))/track().duration;t=v/scene().duration});const curves=$('#curveControls');curves.replaceChildren();['Початок X','Початок Y','Кінець X','Кінець Y'].forEach((label,i)=>control(curves,label,track().curve[i],0,1,.01,v=>track().curve[i]=v));updateCurve();$('#panelContext').textContent=$('#selection').textContent;seek();
 const materialRoot=$('#material');
 if(tab==='dock'){
  materialRoot.replaceChildren();
  const sharedTitle=document.createElement('h3');sharedTitle.textContent='Спільне скло дока';materialRoot.append(sharedTitle);
  const sharedNote=document.createElement('p');sharedNote.className='hint';sharedNote.textContent='Одна настройка одразу застосовується до поля введення та всіх скляних капсул дока. Не анімується і не має ключів.';materialRoot.append(sharedNote);
  const sharedControls=document.createElement('div');materialRoot.append(sharedControls);fields(sharedControls,profile.material,[['color','Колір',0,0,0,'color'],['opacity','Прозорість',0,1,.01],['blur','Розмиття',0,40,1],['lens','Лінза / блиск',0,3,.05],['borderHorizontal','Обводка зверху/знизу, px',0,8,.1],['borderVertical','Обводка зліва/справа, px',0,8,.1],['borderOpacity','Прозорість обводки',0,1,.01],['accent','Активна кнопка',0,0,0,'color']]);
  const indicatorTitle=document.createElement('h3');indicatorTitle.textContent='Скло ковзного індикатора';materialRoot.append(indicatorTitle);
  const indicatorNote=document.createElement('p');indicatorNote.className='hint';indicatorNote.textContent='Окремий матеріал для рухомої підсвітки під вибраною кнопкою; також глобальний для всіх переходів, без ключів.';materialRoot.append(indicatorNote);
  const indicatorControls=document.createElement('div');materialRoot.append(indicatorControls);fields(indicatorControls,profile.indicatorMaterial,[['color','Колір індикатора',0,0,0,'color'],['opacity','Прозорість індикатора',0,1,.01],['blur','Розмиття індикатора',0,40,1],['lens','Лінза індикатора',0,3,.05],['border','Обводка індикатора, px',0,8,.1],['borderOpacity','Прозорість обводки індикатора',0,1,.01]]);
 }else fields(materialRoot,profile.popups[popup],[['color','Колір',0,0,0,'color'],['opacity','Прозорість скла',0,1,.01],['blur','Розмиття',0,40,1],['radius','Кути, px',0,80,1],['border','Обводка, px',0,8,.1]]);
 if(tab==='popup'){const q=profile.popups[popup];control($('#material'),'Ширина вікна, px',q.width|| (popup==='drawer'?360:480),200,900,1,v=>q.width=v);control($('#material'),'Макс. висота, % екрана',q.height||90,20,100,1,v=>q.height=v)}
 const l=$('#liquid');fields(l,profile.liquid,[['strength','Деформація',0,3,.05],['reach','Відстань злиття, px',0,250,1],['neck','Товщина перешийка',0,3,.05],['tension','Натяг краю',.05,.9,.01],['blur','М’якість злиття',0,8,.1]]);const label=document.createElement('label'),toggle=document.createElement('input');toggle.type='checkbox';toggle.checked=profile.liquid.enabled;toggle.onchange=()=>change(()=>profile.liquid.enabled=toggle.checked);label.append(toggle,' Зливання крапель');l.prepend(label);$('#undo').disabled=!history.length;$('#redo').disabled=!future.length;
}
function stop(){playing=false;cancelAnimationFrame(raf);$('#play').textContent='▶ Відтворити'}
$('#play').onclick=()=>{if(!profile)return;if(playing){stop();return}playing=true;$('#play').textContent='Ⅱ Пауза';if(t>=1)t=0;const start=performance.now()-t*scene().duration;const tick=now=>{t=((now-start)/scene().duration);if(t>=1){if($('#loop').checked)t%=1;else{t=1;seek();stop();return}}seek();raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick)};
$('#scrub').oninput=e=>{stop();t=+e.target.value/1000;seek()};$('#start').onclick=()=>{stop();t=0;seek()};
$('#transition').onchange=e=>{stop();transition=e.target.value;selected=0;t=0;render();persist()};$('#popup').onchange=e=>{popup=e.target.value;selected=0;t=0;render();persist()};$('#element').onchange=()=>selectKey(0);
function setTab(value){stop();tab=value;t=0;selected=0;$('#dockTab').classList.toggle('selected',tab==='dock');$('#popupTab').classList.toggle('selected',tab==='popup');$('#transition').parentElement.hidden=tab!=='dock';$('#popupChoice').hidden=tab==='dock';$('#element').hidden=tab!=='dock';render();persist()}
$('#dockTab').onclick=()=>setTab('dock');$('#popupTab').onclick=()=>setTab('popup');
$('#add').onclick=()=>{if(!profile)return;const local=(t*scene().duration-(track().delay||0))/track().duration;if(local<=0||local>=1){status('Обери час усередині доріжки елемента');return}if(track().frames.some(f=>Math.abs(f.t-local)<.005)){status('У цього елемента тут уже є ключ');return}change(()=>{let f;if(tab==='dock'){const api=iframe.contentWindow.VFMotion;api.set(profile);const s=api.sample(transition,t),r=profile.referenceWidth/s.w;for(const k of ['entry','entryRim','entryBulge','nav','active','navRim','activeRim','neck','drop','drop2','drop3','shine','entryHtml','indicator']){s[k][0]*=r;s[k][2]*=r}for(const b of s.buttons){b[0]*=r;b[2]*=r}s.w=profile.referenceWidth;f={t:local,state:s}}else{const fs=track().frames;let i=0;while(i<fs.length-2&&fs[i+1].t<local)i++;const a=fs[i],b=fs[i+1],u=iframe.contentWindow.VFMotion.ease((local-a.t)/(b.t-a.t),track().curve);f={t:local,v:a.v.map((v,j)=>v+(b.v[j]-v)*u)}}track().frames.push(f);track().frames.sort((a,b)=>a.t-b.t);selected=track().frames.indexOf(f)},true)};
$('#remove').onclick=()=>{if(selected===0||selected===track().frames.length-1)return;change(()=>{track().frames.splice(selected,1);selected--;t=keyMs(track().frames[selected])/scene().duration},true)};
const panelNames={geometry:'Форма та позиція',timing:'Тривалість і ключі',curvePanel:'Крива цього елемента',material:'Скло',liquid:'Рідина',project:'Проєкт'};
const settingsPanel=$('#settingsPanel'),toolstrip=document.querySelector('.toolstrip');
function showSettings(button){
 if(!profile)return;
 stop();render();
 document.querySelectorAll('[data-section]').forEach(s=>s.hidden=s.id!==button.dataset.panel);
 settingsPanel.scrollTop=0;
 document.querySelectorAll('[data-panel]').forEach(b=>{const active=b===button;b.classList.toggle('active-category',active);b.setAttribute('aria-pressed',String(active))});
 $('#panelTitle').textContent=panelNames[button.dataset.panel];
 $('#panelContext').textContent=button.dataset.panel==='material'?'Спільне налаштування — поза таймлайном і ключами.':$('#selection').textContent;
 const mobile=matchMedia('(max-width:849px)').matches;
 document.body.classList.toggle('inspector-open',mobile);
 if(mobile){document.body.style.setProperty('--toolstrip-height',`${toolstrip.getBoundingClientRect().height}px`);if(!settingsPanel.open)settingsPanel.show()}
 else if(!settingsPanel.open)settingsPanel.showModal();
}
document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>showSettings(b));
$('#closePanel').onclick=()=>settingsPanel.close();
settingsPanel.addEventListener('close',()=>{document.body.classList.remove('inspector-open');document.body.style.removeProperty('--toolstrip-height')});
settingsPanel.onclick=e=>{if(e.target!==settingsPanel||!settingsPanel.matches(':modal'))return;const r=settingsPanel.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)settingsPanel.close()};
document.querySelectorAll('[data-curve]').forEach(b=>b.onclick=()=>change(()=>track().curve=b.dataset.curve.split(',').map(Number),true));
$('#undo').onclick=()=>{if(!history.length)return;future.push(JSON.stringify(profile));profile=JSON.parse(history.pop());selected=0;persist();render()};$('#redo').onclick=()=>{if(!future.length)return;history.push(JSON.stringify(profile));profile=JSON.parse(future.pop());selected=0;persist();render()};
$('#width').onchange=e=>{iframe.style.width=e.target.value+'px';setTimeout(()=>send('preset',{profile}),100)};
const previewExpand=$('#previewExpand');function setPreviewFocus(open){document.body.classList.toggle('preview-focus',open);previewExpand.setAttribute('aria-pressed',String(open));previewExpand.querySelector('span').textContent=open?'Повернутися':'На весь екран'}previewExpand.onclick=()=>setPreviewFocus(!document.body.classList.contains('preview-focus'));addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('preview-focus'))setPreviewFocus(false)});
$('#apply').onclick=()=>send('save',{profile});$('#disable').onclick=()=>{localStorage.removeItem(key);status('Пресет вимкнено. Перезавантаж застосунок.')};$('#reset').onclick=()=>{if(confirm('Скинути всі форми та налаштування чернетки?')){remember();send('reset')}};
$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(profile,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='voice-finance-motion.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('#import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>12000000)throw Error('Файл завеликий');const api=iframe.contentWindow.VFMotion,p=api.upgradeTracks(api.validate(JSON.parse(await file.text())));remember();profile=p;selected=0;t=0;persist();render()}catch(err){status('Імпорт: '+err.message)}e.target.value=''};
addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==iframe.contentWindow||e.data?.source!=='vf-motion')return;const d=e.data;if(d.type==='ready'){profile=iframe.contentWindow.VFMotion.upgradeTracks(d.profile);selected=0;t=0;render();persist()}if(d.type==='error')status('Помилка: '+d.message);if(d.type==='saved')status('Застосовано! Відкрий або перезавантаж Demo.')});
})();
